apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-app-ingress
  namespace: chat-app
  labels:
    name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-terget: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontend
            port: 
              number: 80
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: backend
            port: 
              number: 5001
      - pathType: Prefix
        path: "/mongo"
        backend:
          service:
            name: mongodb
            port:
              number: 27017
      - pathType: Prefix
        path: "/debug"
        backend:
          service:
            name: backend
            port:
              number: 9229
