apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: chat-app
spec:
  selector:
    matchLabels:
      app: mongodb-selec
  template:
    metadata:
      labels:
        app: mongodb-selec
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 999
        fsGroup: 999
      serviceAccountName: mongodb-sa
      containers:
      - name: myapp
        image: mongo:7.0
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
          privileged: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "root"
        volumeMounts:
        - mountPath: "/mnt/data"
          name: mongo-pv
      volumes:
      - name: mongo-pv
        persistentVolumeClaim:
          claimName: mongo-pvc
